# 日英変換
to_ja = {
    "fin": {
        "Amortization": "償却費",
        "Amortization Of Intangibles Income Statement": "損益計算書の無形資産償却費",
        "Average Dilution Earnings": "平均希薄化利益",
        "Basic Average Shares": "基本平均株式数",
        "Basic EPS": "基本EPS",
        "Cost Of Revenue": "売上原価",
        "Depreciation Amortization Depletion Income Statement": "損益計算書の減価償却費・償却費・枯渇費",
        "Depreciation And Amortization In Income Statement": "損益計算書の減価償却費及び償却費",
        "Depreciation Income Statement": "損益計算書の減価償却費",
        "Diluted Average Shares": "希薄化後平均株式数",
        "Diluted EPS": "希薄化後EPS",
        "Diluted NI Availto Com Stockholders": "希薄化後株主帰属純利益",
        "Earnings From Equity Interest": "持分法による投資利益",
        "EBIT": "利払い・税引前利益(EBIT)",
        "EBITDA": "利払い・税引前・減価償却前利益(EBITDA)",
        "Gain On Sale Of Business": "事業売却益",
        "Gain On Sale Of Ppe": "有形固定資産売却益",
        "Gain On Sale Of Security": "有価証券売却益",
        "General And Administrative Expense": "一般管理費",
        "Gross Profit": "売上総利益",
        "Impairment Of Capital Assets": "資本資産の減損",
        "Insurance And Claims": "保険及び請求",
        "Interest Expense": "支払利息",
        "Interest Expense Non Operating": "営業外支払利息",
        "Interest Income": "受取利息",
        "Interest Income Non Operating": "営業外受取利息",
        "Minority Interests": "少数株主持分",
        "Net Income": "純利益",
        "Net Income Common Stockholders": "普通株主帰属純利益",
        "Net Income Continuous Operations": "継続事業純利益",
        "Net Income Discontinuous Operations": "非継続事業純利益",
        "Net Income From Continuing And Discontinued Operation": "継続・非継続事業純利益",
        "Net Income From Continuing Operation Net Minority Interest": "継続事業純利益（少数株主持分控除後）",
        "Net Income Including Noncontrolling Interests": "非支配株主持分を含む純利益",
        "Net Interest Income": "純利息収益",
        "Net Non Operating Interest Income Expense": "営業外純利息収益（費用）",
        "Net Policyholder Benefits And Claims": "契約者給付金及び請求額純額",
        "Normalized EBITDA": "調整後EBITDA",
        "Normalized Income": "調整後利益",
        "Occupancy And Equipment": "施設及び設備費用",
        "Operating Expense": "営業費用",
        "Operating Income": "営業利益",
        "Operating Revenue": "営業収益",
        "Other Gand A": "その他一般管理費",
        "Other Income Expense": "その他収益（費用）",
        "Other Non Interest Expense": "その他非利息費用",
        "Other Non Operating Income Expenses": "その他営業外収益（費用）",
        "Other Operating Expenses": "その他営業費用",
        "Other Special Charges": "その他特別損失",
        "Otherunder Preferred Stock Dividend": "優先株式配当控除後その他",
        "Pretax Income": "税引前利益",
        "Reconciled Depreciation": "調整後減価償却費",
        "Reconciled Cost Of Revenue": "調整後売上原価",
        "Rent And Landing Fees": "賃借料及び着陸料",
        "Rent Expense Supplemental": "賃借料費用補足",
        "Research And Development": "研究開発費",
        "Restructuring And Mergern Acquisition": "リストラ及び合併・買収費用",
        "Salaries And Wages": "給与及び賃金",
        "Selling And Marketing Expense": "販売費及びマーケティング費用",
        "Selling General And Administration": "販売費及び一般管理費",
        "Special Income Charges": "特別利益（損失）",
        "Tax Effect Of Unusual Items": "異常項目の税効果",
        "Tax Provision": "税金費用",
        "Tax Rate For Calcs": "計算用税率",
        "Total Expenses": "総費用",
        "Total Operating Income As Reported": "報告された営業利益合計",
        "Total Other Finance Cost": "その他の金融費用合計",
        "Total Revenue": "総収益",
        "Total Unusual Items": "異常項目合計",
        "Total Unusual Items Excluding Goodwill": "のれんを除く異常項目合計",
        "Write Off": "償却",
    },
    "bs": {
        "Accounts Payable": "買掛金",
        "Accounts Receivable": "売掛金",
        "Accumulated Depreciation": "減価償却累計額",
        "Additional Paid In Capital": "資本剰余金",
        "Allowance For Doubtful Accounts Receivable": "売掛金貸倒引当金",
        "Assets Held For Sale Current": "売却目的資産（流動）",
        "Available For Sale Securities": "売却可能有価証券",
        "Buildings And Improvements": "建物及び改良",
        "Capital Lease Obligations": "資本リース債務",
        "Capital Stock": "資本金",
        "Cash And Cash Equivalents": "現金及び現金同等物",
        "Cash Equivalents": "現金同等物",
        "Cash Cash Equivalents And Federal Funds Sold": "現金・現金同等物及び連邦基金売却",
        "Cash Cash Equivalents And Short Term Investments": "現金・現金同等物及び短期投資",
        "Cash Financial": "現金（金融）",
        "Commercial Paper": "コマーシャルペーパー",
        "Common Stock": "普通株式",
        "Common Stock Equity": "普通株式資本",
        "Construction In Progress": "建設仮勘定",
        "Current Accrued Expenses": "流動未払費用",
        "Current Assets": "流動資産",
        "Current Capital Lease Obligation": "流動資本リース債務",
        "Current Deferred Assets": "流動繰延資産",
        "Current Deferred Liabilities": "流動繰延負債",
        "Current Deferred Revenue": "流動繰延収益",
        "Current Deferred Taxes Liabilities": "流動繰延税金負債",
        "Current Debt": "短期流動負債",
        "Current Debt And Capital Lease Obligation": "短期流動負債及び資本リース債務",
        "Current Notes Payable": "流動支払手形",
        "Current Liabilities": "流動負債",
        "Current Provisions": "流動引当金",
        "Defined Pension Benefit": "確定給付年金",
        "Derivative Product Liabilities": "デリバティブ商品負債",
        "Dividends Payable": "未払配当金",
        "Employee Benefits": "従業員給付費用",
        "Financial Assets": "金融資産",
        "Financial Assets Designatedas Fair Value Through Profitor Loss Total": "時価評価損益計上金融資産合計",
        "Finished Goods": "製品",
        "Fixed Assets Revaluation Reserve": "固定資産再評価準備金",
        "Foreign Currency Translation Adjustments": "外国通貨換算調整勘定",
        "Gains Losses Not Affecting Retained Earnings": "利益剰余金に影響しない損益",
        "Goodwill": "のれん",
        "Goodwill And Other Intangible Assets": "のれん及びその他無形資産",
        "Gross Accounts Receivable": "売掛金総額",
        "Gross PPE": "有形固定資産総額",
        "Hedging Assets Current": "ヘッジ資産（流動）",
        "Held To Maturity Securities": "満期保有目的有価証券",
        "Income Tax Payable": "未払法人税等",
        "Inventory": "棚卸資産",
        "Invested Capital": "投下資本",
        "Investment Properties": "投資不動産",
        "Investments And Advances": "投資及び前渡金",
        "Investments In Other Ventures Under Equity Method": "持分法適用その他事業への投資",
        "Investmentsin Associatesat Cost": "関連会社投資（原価）",
        "Investmentsin Joint Venturesat Cost": "共同支配企業投資（原価）",
        "Investmentin Financial Assets": "金融資産への投資",
        "Investmentsin Subsidiariesat Cost": "子会社投資（原価）",
        "Land And Improvements": "土地及び改良",
        "Leases": "リース債務",
        "Liabilities Heldfor Sale Non Current": "売却目的負債（非流動）",
        "Long Term Capital Lease Obligation": "長期資本リース債務",
        "Long Term Debt": "長期負債",
        "Long Term Debt And Capital Lease Obligation": "長期負債及び資本リース債務",
        "Long Term Equity Investment": "長期株式投資",
        "Long Term Provisions": "長期引当金",
        "Machinery Furniture Equipment": "機械・什器・備品",
        "Minimum Pension Liabilities": "最低年金債務",
        "Minority Interest": "少数株主持分",
        "Net Debt": "純負債",
        "Net PPE": "有形固定資産純額",
        "Net Tangible Assets": "純有形資産",
        "Non Current Deferred Taxes Assets": "非流動繰延税金資産",
        "Non Current Deferred Taxes Liabilities": "非流動繰延税金負債",
        "Non Current Pension And Other Postretirement Benefit Plans": "非流動年金及びその他退職給付制度",
        "Non Current Prepaid Assets": "非流動前払資産",
        "Non Current Accounts Receivable": "非流動売掛金",
        "Non Current Accrued Expenses": "非流動未払費用",
        "Non Current Deferred Assets": "非流動繰延資産",
        "Non Current Deferred Liabilities": "非流動繰延負債",
        "Non Current Deferred Revenue": "非流動繰延収益",
        "Notes Receivable": "受取手形",
        "Ordinary Shares Number": "普通株式数",
        "Other Current Assets": "その他流動資産",
        "Other Current Borrowings": "その他流動借入金",
        "Other Current Liabilities": "その他流動負債",
        "Other Equity Interest": "その他資本項目",
        "Other Equity Adjustments": "その他資本調整項目",
        "Other Intangible Assets": "その他無形資産",
        "Other Inventories": "その他棚卸資産",
        "Other Investments": "その他投資",
        "Other Non Current Assets": "その他非流動資産",
        "Other Non Current Liabilities": "その他非流動負債",
        "Other Payable": "その他支払勘定",
        "Other Properties": "その他資産",
        "Other Receivables": "その他受取勘定",
        "Other Short Term Investments": "その他短期投資",
        "Payables": "支払勘定",
        "Payables And Accrued Expenses": "支払勘定及び未払費用",
        "Pensionand Other Post Retirement Benefit Plans Current": "年金及びその他退職給付制度（流動）",
        "Prepaid Assets": "前払資産",
        "Preferred Shares Number": "優先株式数",
        "Preferred Securities Outside Stock Equity": "優先証券（株主持分外）",
        "Properties": "資産",
        "Raw Materials": "原材料",
        "Receivables": "受取勘定",
        "Receivables Adjustments Allowances": "受取勘定調整引当金",
        "Restricted Cash": "制限付き現金",
        "Retained Earnings": "利益剰余金",
        "Share Issued": "発行済株式数",
        "Stockholders Equity": "株主資本",
        "Tangible Book Value": "有形簿価",
        "Taxes Receivable": "未収税金",
        "Total Assets": "総資産",
        "Total Capitalization": "総資本",
        "Total Debt": "総負債",
        "Total Equity Gross Minority Interest": "総資本（少数株主持分控除前）",
        "Total Liabilities Net Minority Interest": "総負債（少数株主持分控除後）",
        "Total Non Current Assets": "総非流動資産",
        "Total Non Current Liabilities Net Minority Interest": "総非流動負債（少数株主持分控除後）",
        "Total Tax Payable": "未払税金合計",
        "Tradeand Other Payables Non Current": "売掛金及びその他支払勘定（非流動）",
        "Trading Securities": "売買目的有価証券",
        "Treasury Shares Number": "自己株式数",
        "Treasury Stock": "自己株式",
        "Unrealized Gain Loss": "未実現損益",
        "Work In Process": "仕掛品",
        "Working Capital": "運転資本",
    },
    "pl": {
        "Amortization": "償却費",
        "Amortization Of Intangibles Income Statement": "損益計算書の無形資産償却費",
        "Average Dilution Earnings": "平均希薄化利益",
        "Basic Average Shares": "基本平均株式数",
        "Basic EPS": "基本EPS",
        "Cost Of Revenue": "売上原価",
        "Depreciation Amortization Depletion Income Statement": "損益計算書の減価償却費・償却費・枯渇費",
        "Depreciation And Amortization In Income Statement": "損益計算書の減価償却費及び償却費",
        "Depreciation Income Statement": "損益計算書の減価償却費",
        "Diluted Average Shares": "希薄化後平均株式数",
        "Diluted EPS": "希薄化後EPS",
        "Diluted NI Availto Com Stockholders": "希薄化後株主帰属純利益",
        "Earnings From Equity Interest": "持分法による投資利益",
        "EBIT": "利払い・税引前利益(EBIT)",
        "EBITDA": "利払い・税引前・減価償却前利益(EBITDA)",
        "Gain On Sale Of Business": "事業売却益",
        "Gain On Sale Of Ppe": "有形固定資産売却益",
        "Gain On Sale Of Security": "有価証券売却益",
        "General And Administrative Expense": "一般管理費",
        "Gross Profit": "売上総利益",
        "Impairment Of Capital Assets": "資本資産の減損",
        "Insurance And Claims": "保険及び請求",
        "Interest Expense": "支払利息",
        "Interest Expense Non Operating": "営業外支払利息",
        "Interest Income": "受取利息",
        "Interest Income Non Operating": "営業外受取利息",
        "Minority Interests": "少数株主持分",
        "Net Income": "純利益",
        "Net Income Common Stockholders": "普通株主帰属純利益",
        "Net Income Continuous Operations": "継続事業純利益",
        "Net Income Discontinuous Operations": "非継続事業純利益",
        "Net Income From Continuing And Discontinued Operation": "継続・非継続事業純利益",
        "Net Income From Continuing Operation Net Minority Interest": "継続事業純利益（少数株主持分控除後）",
        "Net Income Including Noncontrolling Interests": "非支配株主持分を含む純利益",
        "Net Interest Income": "純利息収益",
        "Net Non Operating Interest Income Expense": "営業外純利息収益（費用）",
        "Net Policyholder Benefits And Claims": "契約者給付金及び請求額純額",
        "Normalized EBITDA": "調整後EBITDA",
        "Normalized Income": "調整後利益",
        "Occupancy And Equipment": "施設及び設備費用",
        "Operating Expense": "営業費用",
        "Operating Income": "営業利益",
        "Operating Revenue": "営業収益",
        "Other Gand A": "その他一般管理費",
        "Other Income Expense": "その他収益（費用）",
        "Other Non Interest Expense": "その他非利息費用",
        "Other Non Operating Income Expenses": "その他営業外収益（費用）",
        "Other Operating Expenses": "その他営業費用",
        "Other Special Charges": "その他特別損失",
        "Otherunder Preferred Stock Dividend": "優先株式配当控除後その他",
        "Pretax Income": "税引前利益",
        "Reconciled Cost Of Revenue": "調整後売上原価",
        "Reconciled Depreciation": "調整後減価償却費",
        "Rent And Landing Fees": "賃借料及び着陸料",
        "Rent Expense Supplemental": "賃借料費用補足",
        "Research And Development": "研究開発費",
        "Restructuring And Mergern Acquisition": "リストラ及び合併・買収費用",
        "Salaries And Wages": "給与及び賃金",
        "Selling And Marketing Expense": "販売費及びマーケティング費用",
        "Selling General And Administration": "販売費及び一般管理費",
        "Special Income Charges": "特別利益（損失）",
        "Tax Effect Of Unusual Items": "異常項目の税効果",
        "Tax Provision": "税金費用",
        "Tax Rate For Calcs": "計算用税率",
        "Total Expenses": "総費用",
        "Total Operating Income As Reported": "報告された営業利益合計",
        "Total Other Finance Cost": "その他の金融費用合計",
        "Total Revenue": "総収益",
        "Total Unusual Items": "異常項目合計",
        "Total Unusual Items Excluding Goodwill": "のれんを除く異常項目合計",
        "Write Off": "償却",
    },
    "cf": {
        "Amortization Cash Flow": "キャッシュフローの償却費",
        "Amortization Of Intangibles": "無形資産償却費",
        "Asset Impairment Charge": "資産減損損失",
        "Beginning Cash Position": "期首現金残高",
        "Cash From Discontinued Financing Activities": "非継続的な財務活動によるキャッシュフロー",
        "Cash From Discontinued Investing Activities": "非継続的な投資活動によるキャッシュフロー",
        "Cash From Discontinued Operating Activities": "非継続的な営業活動によるキャッシュフロー",
        "Capital Expenditure": "資本的支出",
        "Capital Expenditure Reported": "報告された資本的支出",
        "Cash Dividends Paid": "支払配当金",
        "Cash Flow From Continuing Financing Activities": "継続的な財務活動によるキャッシュフロー",
        "Cash Flow From Continuing Investing Activities": "継続的な投資活動によるキャッシュフロー",
        "Cash Flow From Continuing Operating Activities": "継続的な営業活動によるキャッシュフロー",
        "Change In Account Payable": "買掛金の増減",
        "Change In Accrued Expense": "未払費用の増減",
        "Change In Income Tax Payable": "未払法人税等の増減",
        "Change In Inventory": "棚卸資産の増減",
        "Change In Other Current Assets": "その他流動資産の増減",
        "Change In Other Current Liabilities": "その他流動負債の増減",
        "Change In Other Working Capital": "その他運転資本の増減",
        "Change In Payable": "支払勘定の増減",
        "Change In Payables And Accrued Expense": "支払勘定及び未払費用の増減",
        "Change In Prepaid Assets": "前払資産の増減",
        "Change In Receivables": "受取勘定の増減",
        "Change In Tax Payable": "未払税金の増減",
        "Change In Working Capital": "運転資本の増減",
        "Changes In Account Receivables": "売掛金の増減",
        "Changes In Cash": "現金の増減",
        "Common Stock Dividend Paid": "支払普通株式配当金",
        "Common Stock Issuance": "普通株式発行",
        "Common Stock Payments": "普通株式支払",
        "Deferred Income Tax": "繰延法人税等",
        "Deferred Tax": "繰延税金",
        "Depreciation": "減価償却費",
        "Depreciation And Amortization": "減価償却費及び償却費",
        "Depreciation Amortization Depletion": "減価償却費・償却費・枯渇費",
        "Dividend Paid Cfo": "支払配当金（営業活動によるキャッシュフロー）",
        "Dividend Received Cfo": "受取配当金（営業活動によるキャッシュフロー）",
        "Dividends Received Cfi": "受取配当金（投資活動によるキャッシュフロー）",
        "Earnings Losses From Equity Investments": "持分法適用投資からの利益（損失）",
        "Effect Of Exchange Rate Changes": "為替変動の影響",
        "End Cash Position": "期末現金残高",
        "Financing Cash Flow": "キャッシュフローの財務活動による収支",
        "Free Cash Flow": "フリーキャッシュフロー",
        "Gain Loss On Investment Securities": "投資有価証券の損益",
        "Gain Loss On Sale Of Business": "事業売却の損益",
        "Gain Loss On Sale Of PPE": "有形固定資産売却の損益",
        "Income Tax Paid Supplemental Data": "支払法人税等（補足データ）",
        "Interest Paid Cff": "支払利息（キャッシュフロー計算書）",
        "Interest Paid Cfo": "支払利息（営業活動によるキャッシュフロー）",
        "Interest Paid Supplemental Data": "支払利息（補足データ）",
        "Interest Received Cfi": "受取利息（投資活動によるキャッシュフロー）",
        "Interest Received Cfo": "受取利息（営業活動によるキャッシュフロー）",
        "Investing Cash Flow": "キャッシュフローの投資活動による収支",
        "Issuance Of Capital Stock": "株式発行",
        "Issuance Of Debt": "負債発行",
        "Long Term Debt Issuance": "長期負債発行",
        "Long Term Debt Payments": "長期負債返済",
        "Net Business Purchase And Sale": "事業買収及び売却純額",
        "Net Common Stock Issuance": "普通株式発行純額",
        "Net Foreign Currency Exchange Gain Loss": "外国通貨為替差益（損失）純額",
        "Net Income From Continuing Operations": "継続事業純利益",
        "Net Intangibles Purchase And Sale": "無形資産買収及び売却純額",
        "Net Investment Purchase And Sale": "投資買収及び売却純額",
        "Net Investment Properties Purchase And Sale": "投資不動産買収及び売却純額",
        "Net Issuance Payments Of Debt": "負債発行及び返済純額",
        "Net Long Term Debt Issuance": "長期負債発行純額",
        "Net Other Financing Charges": "その他の財務費用純額",
        "Net Other Investing Changes": "その他の投資活動による変動純額",
        "Net Preferred Stock Issuance": "優先株式発行純額",
        "Net PPE Purchase And Sale": "有形固定資産買収及び売却純額",
        "Net Short Term Debt Issuance": "短期負債発行純額",
        "Operating Cash Flow": "営業活動によるキャッシュフロー",
        "Operating Gains Losses": "営業損益",
        "Other Cash Adjustment Outside Changein Cash": "現金の増減以外のその他の現金調整",
        "Other Cash Adjustment Inside Changein Cash": "現金の増減内のその他の現金調整",
        "Other Non Cash Items": "その他の非現金項目",
        "Pension And Employee Benefit Expense": "年金及び従業員給付費用",
        "Preferred Stock Payments": "優先株式支払",
        "Provisionand Write Offof Assets": "資産の引当金及び償却",
        "Purchase Of Business": "事業買収",
        "Purchase Of Intangibles": "無形資産購入",
        "Purchase Of Investment": "投資購入",
        "Purchase Of Investment Properties": "投資不動産購入",
        "Purchase Of PPE": "有形固定資産購入",
        "Repayment Of Debt": "負債返済",
        "Repurchase Of Capital Stock": "自己株式取得",
        "Sale Of Business": "事業売却",
        "Sale Of Investment": "投資売却",
        "Sale Of Intangibles": "無形資産売却",
        "Sale Of Investment Properties": "投資不動産売却",
        "Sale Of PPE": "有形固定資産売却",
        "Short Term Debt Issuance": "短期負債発行",
        "Short Term Debt Payments": "短期負債返済",
        "Stock Based Compensation": "株式報酬",
        "Taxes Refund Paid": "税金還付（支払）",
        "Unrealized Gain Loss On Investment Securities": "投資有価証券の未実現損益",
    },
}
